# Generated by Django 5.0.6 on 2024-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hindu Cards', 'Hindu Cards'), ('Muslim Cards', 'Muslim Cards'), ('Worship Cards', 'Worship Cards')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], default='In stock', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
